In [2]:
import numpy as np
array1 = np.array(range(30))
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [9]:
array2=np.array(range(30)).reshape(5,6)
array2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [11]:
b=array2.ravel(order='F')
b

array([ 0,  6, 12, 18, 24,  1,  7, 13, 19, 25,  2,  8, 14, 20, 26,  3,  9,
       15, 21, 27,  4, 10, 16, 22, 28,  5, 11, 17, 23, 29])

In [14]:
c=np.hsplit(array2,[0,1,2])
c

[array([], shape=(5, 0), dtype=int32),
 array([[ 0],
        [ 6],
        [12],
        [18],
        [24]]),
 array([[ 1],
        [ 7],
        [13],
        [19],
        [25]]),
 array([[ 2,  3,  4,  5],
        [ 8,  9, 10, 11],
        [14, 15, 16, 17],
        [20, 21, 22, 23],
        [26, 27, 28, 29]])]